sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t steelman72/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true steelman72/react-test npm run test -- --coverage

after_success:
  - docker build -t shankarar/multi-client ./client
  - docker build -t shankarar/multi-nginx ./nginx
  - docker build -t shankarar/multi-server ./server
  - docker build -t shankarar/multi-worker ./worker

  # Push images to dockerhub
  # Enter docker credentials
  # Using env vars entered in Travis project
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shankarar/multi-client
  - docker push shankarar/multi-nginx
  - docker push shankarar/multi-server
  - docker push shankarar/multi-worker
